### ISSUE TITLE
minor: migrate Gradle configuration to newer version

### ISSUE THREAD

**Issue by peterblazejewicz** [nasa-jpl/osr-android-app#2]
Hi,
I'm not active Android developer, so could be wrong here. I'm running the project in the local emulator. After the project setup, gradle configuration and build, the compiler spills out warnings about obsolete Gradle properties, which seems to be described here:
https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration

```bash
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.	
Configuration 'androidTestCompile' is obsolete and has been replaced with 'androidTestImplementation' and 'androidTestApi'.	
Configuration 'androidTestApi' is obsolete and has been replaced with 'androidTestImplementation'.	
Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.	
Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.	
```

Thanks!

**Comment by sachinsshetty** [comment]
Created a pull request(#4 ) to fix these warnings
